package com.finalweek.task;

public enum TaskStage {
    UPLOADED,
    CONTENT_EXTRACTED,
    CHUNKED,
    EMBEDDING_COMPLETED,
    CONTEXT_RETRIEVED,
    OUTLINE_GENERATED,
    PLAN_CONTEXT_RETRIEVED,
    PLAN_GENERATED,
    CHAT_CONTEXT_RETRIEVED,
    CHAT_ANSWER_GENERATED,
    REQUIREMENTS_ANALYZED,
    QUESTIONS_GENERATED,
    PAPER_VALIDATED,
    PDFS_GENERATED,
    COMPLETED
}
